package main

import (
	"net/http"

	log "github.com/sirupsen/logrus"

	"flag"

	"fmt"

	"github.com/fgruchala/twall-middle-go/service"
	"github.com/fgruchala/twall-middle-go/webservice"
	"github.com/gorilla/mux"
)

func main() {
	log.SetFormatter(&log.TextFormatter{
		ForceColors:   true,
		FullTimestamp: true,
	})

	port := flag.Int("port", 3002, "Port on which Twall is listening")
	consumerKey := flag.String("consumerKey", "", "Consumer key generated by Twitter. Go https://apps.twitter.com")
	consumerSecret := flag.String("consumerSecret", "", "Consumer secret generated by Twitter. Go https://apps.twitter.com")
	flag.Parse()

	tweetService := service.NewTweetService(consumerKey, consumerSecret)

	router := mux.NewRouter().StrictSlash(true)
	webservice.NewTweetWebservice(router, tweetService)

	log.WithFields(log.Fields{"port": *port}).Info("Starting server ...")
	log.Fatal(http.ListenAndServe(fmt.Sprintf(":%v", *port), router))
}
